pub const V2_COMMANDS: &[(&str, &str)] = &[
    ("listToolDefinitions", "list_tool_definitions"),
    ("previewAgentRun", "preview_agent_run"),
    ("startAgentRun", "start_agent_run"),
    ("startStoryArchitectRun", "start_story_architect_run"),
    ("startRevisionRun", "start_revision_run"),
    ("cancelAgentRun", "cancel_agent_run"),
    ("getAgentRun", "get_agent_run"),
    ("listRunEvents", "list_run_events"),
    ("getActiveAgentRun", "get_active_agent_run"),
    ("getProjectWorkspace", "get_project_workspace"),
    ("getArtifact", "get_artifact_v2"),
    ("listArtifactSummaries", "list_artifact_summaries"),
    ("listIndexJobs", "list_index_jobs"),
    ("listActionProposals", "list_action_proposals_v2"),
    ("applyActionProposal", "apply_action_proposal"),
    ("rejectActionProposal", "reject_action_proposal"),
    ("listLegacyAgentPrompts", "list_legacy_agent_prompts"),
    ("getProviderCapabilities", "get_provider_capabilities"),
    ("resetAgentPrompt", "reset_agent_prompt"),
];
